# Linear Algebra

## Numpy

In [1]:
import numpy as np

In [5]:
l = [1.0, 2.0, 3.0]
a = np.array(l)
a

array([1., 2., 3.])

In [6]:
print(a.shape)
print(a.dtype)

(3,)
float64


In [7]:
#empty 

In [8]:
a = np.empty([3,3])
print(a)

[[ 6.17779239e-31 -1.23555848e-30  3.08889620e-31]
 [-1.23555848e-30  2.68733969e-30 -8.34001973e-31]
 [ 3.08889620e-31 -8.34001973e-31  4.78778910e-31]]


In [9]:
# zeros
a = np.zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# ones
a = np.ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [13]:
# combining arrays - vstack, hstack
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1, a2)
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3] [4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
a4 = np.hstack((a1, a2))
print(a4)
print(a4.shape)

[1 2 3 4 5 6]
(6,)


In [15]:
## slice, index, reshape

In [19]:
data1D = np.array([11,22,33,44,55])
print(data1D, type(data1D))

[11 22 33 44 55] <class 'numpy.ndarray'>


In [20]:
# 2 dim
data2D = np.array([[11,22], [33,44], [55,66]])
print(data2D, type(data2D))

[[11 22]
 [33 44]
 [55 66]] <class 'numpy.ndarray'>


In [22]:
print(data1D[0], data1D[3])

11 44


In [23]:
print(data1D[-1], data1D[-5])

55 11


In [27]:
print(data2D[0], data2D[0,1], data2D[0,])

[11 22] 22 [11 22]


In [33]:
print(data2D[:], '\n\n\t', data2D[0:2])

[[11 22]
 [33 44]
 [55 66]] 

	 [[11 22]
 [33 44]]


In [34]:
#slicing
data2DB = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
data2DB

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [35]:
X, y = data2DB[:, :-1], data2DB[:, -1]
print(X, '\n\n', y)

[[11 22]
 [44 55]
 [77 88]] 

 [33 66 99]


In [38]:
train, test = data2DB[:2, :], data2DB[2:, :]
print('Train Data- \n', train, '\n Test Data- ', test)

Train Data- 
 [[11 22 33]
 [44 55 66]] 
 Test Data-  [[77 88 99]]


In [39]:
data1D

array([11, 22, 33, 44, 55])

In [50]:
print(data1D.shape, data2D.shape)

(5,) (3, 2)


In [51]:
print(data1D.shape[0], '\t Data2D -', data2D.shape[0], data2D.shape[1])

5 	 Data2D - 3 2


In [52]:
# 1 D to 2 D
print(data1D.reshape(data1D.shape[0], 1) , ' Shape- ',  data1D.reshape(data1D.shape[0], 1).shape) 

[[11]
 [22]
 [33]
 [44]
 [55]]  Shape-  (5, 1)


In [56]:
# any Dim to Single Columns
data1D.reshape(-1, 1)

array([[11],
       [22],
       [33],
       [44],
       [55]])

In [57]:
data2D.reshape(-1, 1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [60]:
#2d to 3d
print(data2D.reshape(data2D.shape[0], data2D.shape[1], 1), data2D.reshape(data2D.shape[0], data2D.shape[1], 1).shape)
# 3 x 2 matrix - 1 array

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]] (3, 2, 1)


## Broadcast

## Matrices

In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a, b, a+b, a-b)

[1 2 3] [4 5 6] [5 7 9] [-3 -3 -3]


In [64]:
print(a * b)

[ 4 10 18]


In [65]:
print(a / b)

[0.25 0.4  0.5 ]


In [67]:
np.linalg.norm(a,1 )

6.0

In [73]:
np.linalg.norm(a , -2)

0.8571428571428571

## Matrix Multiplication, Addition, Subtraction, Division

In [75]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
lower = np.tril(M)
lower

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [77]:
upper = np.triu(M)
upper

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [78]:
d = np.diag(M)
d

array([1, 5, 9])

In [79]:
np.diag(d)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [80]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
V = np.linalg.inv(I)
V

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
V.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Matrix Operations

In [86]:
A = np.array([ [1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
C = A.T
C

array([[1, 3, 5],
       [2, 4, 6]])

In [93]:
A = np.array([[1, 2] , [3,4]])
print(A)
AI = np.linalg.inv(A)  #inverse of matrix
AI

[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
A.dot(AI)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [95]:
np.trace(AI)

-2.4999999999999996

In [96]:
np.linalg.det(A)

-2.0000000000000004

In [97]:
np.linalg.matrix_rank(A)

2

## sparse matrix

In [99]:
import scipy as sc

In [98]:
A = np.array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]])
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [100]:
SA = sc.sparse.csr_matrix(A)
SA

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [101]:
BA = SA.todense()
BA

matrix([[1, 0, 0, 1, 0, 0],
        [0, 0, 2, 0, 0, 1],
        [0, 0, 0, 2, 0, 0]])

In [103]:
sparsity = 1.0 - np.count_nonzero(A) / A.size
sparsity

0.7222222222222222

## Factorise