# Neural Network

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [6]:
iris = load_iris()
#iris

In [8]:
X = iris.data[:, (2,3)]  #petal - length, width
X[0:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [24]:
X.shape

(150, 2)

In [13]:
y = (iris.target == 0).astype('int')  #setosas
y[0:5]

array([1, 1, 1, 1, 1])

In [14]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
y.shape

(150,)

In [26]:
y[0:5].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [15]:
per_clf = Perceptron()
per_clf.fit(X, y)

Perceptron()

In [30]:
np.concatenate((X[0:15] , y[0:15].reshape(-1,1)), axis=1)

array([[1.4, 0.2, 1. ],
       [1.4, 0.2, 1. ],
       [1.3, 0.2, 1. ],
       [1.5, 0.2, 1. ],
       [1.4, 0.2, 1. ],
       [1.7, 0.4, 1. ],
       [1.4, 0.3, 1. ],
       [1.5, 0.2, 1. ],
       [1.4, 0.2, 1. ],
       [1.5, 0.1, 1. ],
       [1.5, 0.2, 1. ],
       [1.6, 0.2, 1. ],
       [1.4, 0.1, 1. ],
       [1.1, 0.1, 1. ],
       [1.2, 0.2, 1. ]])

In [17]:
y_pred = per_clf.predict([[2, 0.5]])
y_pred

array([0])